version: '2'

services:
  otel-collector:
    image: otel/opentelemetry-collector:0.68.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSTEP_ACCESS_TOKEN}"
    ports:
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    depends_on:
      - config-server
      - otel-collector
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSSTEP_ACCESS_TOKEN}"
      OTEL_SERVICE_NAME: "discovery-server"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    entrypoint: [ "./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-javaagent:/etc/opentelemetry-javaagent.jar", "org.springframework.boot.loader.JarLauncher" ]
    ports:
      - 8761:8761

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
     - otel-collector
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSSTEP_ACCESS_TOKEN}"
      OTEL_SERVICE_NAME: "customers-service"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/etc/opentelemetry-javaagent.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
    - 8081:8081

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
     - otel-collector
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSSTEP_ACCESS_TOKEN}"
      OTEL_SERVICE_NAME: "visits-service"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/etc/opentelemetry-javaagent.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8082:8082

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
     - otel-collector
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSSTEP_ACCESS_TOKEN}"
      OTEL_SERVICE_NAME: "vets-service"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/etc/opentelemetry-javaagent.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
     - otel-collector
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSSTEP_ACCESS_TOKEN}"
      OTEL_SERVICE_NAME: "api-gateway"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/etc/opentelemetry-javaagent.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
     - otel-collector
    volumes:
      - ./opentelemetry-javaagent.jar:/etc/opentelemetry-javaagent.jar
    environment:
      LIGHTSTEP_ACCESS_TOKEN: "${LIGHTSSTEP_ACCESS_TOKEN}"
      OTEL_SERVICE_NAME: "admin-server"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-javaagent:/etc/opentelemetry-javaagent.jar", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090
